name: Comment PR

on:
  pull_request_review_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Message Notify
        uses: appleboy/discord-action@v1.0.0
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: "<@&${{ vars.PROGRAMMER_ID }}>\n${{ github.event.comment.user.login }} commented [Pull Request(title: ${{ github.event.pull_request.title }})](<${{ github.event.pull_request.html_url }}>)!\nURL: ${{ github.event.comment.html_url }}"
