name: Approved PR

on:
  issue_comment:
    types: [created]

jobs:
  notify:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Discord Message Notify
        uses: appleboy/discord-action@v1.0.0
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: "<@&${{ vars.PROGRAMMER_ID }}>\n${{ github.event.issue.user.login }} commented [Pull Request(title: ${{ github.event.issue.title }})](<${{ github.event.issue.html_url }}>)!"
